### PR TITLE
Added automatic stale issue handling, automated linting and tox for easy local testing

### PR DESCRIPTION
**Pull request by wolph**

### CODE REVIEW

**Comment by jorenham** [comment]
Ruff can do everything that flake8 does, it just needs a bit of configuration in `pyproject.toml`:
https://beta.ruff.rs/docs/rules/

**Comment by wolph** [comment]
flake8 was giving me complaints about stuff that ruff didn't care about so I added it as well. But I'll look into configuring ruff, less dependencies is always nice

**Comment by wolph** [comment]
There are still quite a few code style rules missing from ruff it seems: https://github.com/astral-sh/ruff/issues/2402

Should I remove flake8 or keep it? :)

**Comment by jorenham** [comment]
> There are still quite a few code style rules missing from ruff it seems: [astral-sh/ruff#2402](https://github.com/astral-sh/ruff/issues/2402)
> 
> Should I remove flake8 or keep it? :)

Ah I didn't know. Considering the scale of the project, let's just stick with ruff for now. Once they support more of flake8 we can always enable it.

**Pull request merged**
